---

  - hosts: database
    become: true
    become_user: root

    tasks:
      - name: Add postgre key
        apt-key:
          url:   https://www.postgresql.org/media/keys/ACCC4CF8.asc
          state: present

      - name: Install Postgre
        apt:
          name: postgresql-{{ postgresql_version }}
          state: present
          update_cache: yes

      - name: Checking PostgreSQL data directory exists
        file:
          path: "{{ postgresql_data_directory }}"
          owner: postgres
          group: postgres
          state: directory
          mode: 0700

      - name: change postgres database directory
        lineinfile:
          path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
          search_string: 'data_directory ='
          line: data_directory = '{{ postgresql_data_directory }}'

  - hosts: app
    become: true
    become_user: root

    tasks:
      - name: Install apt-transport-https
        when: ansible_os_family == "Debian"
        apt:
          name: "apt-transport-https"
          state: present
          update_cache: yes

      - name: Add Docker APT GPG key
        when: ansible_os_family == "Debian"
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg

      - name: Add Docker APT repository
        when: ansible_os_family == "Debian"
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
          state: present
          filename: "docker"

      - name: Add Docker yum reposytory
        when: ansible_os_family == "RedHat"
        yum_repository:
          name: Docker
          description: Docker Repository
          file: docker
          baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
          enabled: yes
          gpgcheck: yes
          gpgkey: https://download.docker.com/linux/centos/gpg

      - name: Install docker engine (RHEL/CentOS)
        when: ansible_os_family == "RedHat"
        yum:
          name: "docker-ce"
          state: present

      - name: Install docker engine (Debian/Ubuntu)
        when: ansible_os_family == "Debian"
        apt:
          update_cache: yes
          name: "docker-ce"
          state: present

      - name: Hold docker version
        when: ansible_os_family == "Debian"
        dpkg_selections:
          name: docker-ce
          selection: hold
